services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.12.0
    container_name: mlflow

    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000

    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}

    ports:
      - "5000:5000"

    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile

    container_name: api

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - mlflow

    restart: unless-stopped